s = set()
n = input("Enter your number: ")
s.add(n)
n = input("Enter your number: ")
s.add(n)
n = input("Enter your number: ")
s.add(n)
n = input("Enter your number: ")
s.add(n)
n = input("Enter your number: ")
s.add(n)
n = input("Enter your number: ")
s.add(n)
n = input("Enter your number: ")
s.add(n)

print(s)